using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using RoadNetworkDefinition;
using GeneticAlgorithm.Plugin;

namespace RoadNetworkSolver
{
    /// <summary>
    /// IGeneticOperator which generates new individuals by randomly making small changes to existing
    /// individuals.
    /// 
    /// This operator should only be used with populations generated by StepPopulator and StepCyclePopulator or
    /// as it assumes that the Edges only connect adjacent points.
    /// </summary>
    public class StepMutator : IGeneticOperator
    {
        /// <summary>
        /// The random number generator used to determine how to change the RoadNetworks
        /// </summary>
        private static Random random = new Random();

        /// <summary>
        /// Initialise a new StepMutator
        /// </summary>
        /// <param name="config">Configuration object (ignored)</param>
        public StepMutator(object config)
        {
        }

        /// <summary>
        /// Process a Network, breaking up all edges into small steps so that edges
        /// only join adjacent points.
        /// </summary>
        /// <param name="network">The RoadNetwork to process</param>
        /// <returns>The resulting RoadNetwork</returns>
        public static RoadNetwork MakeStepped(RoadNetwork network)
        {
            RoadNetwork result = new RoadNetwork(network, false, true);
            int endVertexIndex = result.VertexCount - 1;

            for (int i = 0; i < network.EdgeCount; i++)
            {
                Edge edge = network.GetEdge(i);
                Vertex start = edge.Start.Copy;
                Vertex end = edge.End.Copy;
                Coordinates startCoordinates = start.Coordinates;
                Coordinates endCoordinates = end.Coordinates;

                int dX = endCoordinates.X - startCoordinates.X;
                int dY = endCoordinates.Y - startCoordinates.Y;

                int xStep = 1;
                if (dX < 0)
                {
                    dX = -dX;
                    xStep = -1;
                }

                int yStep = 1;
                if (dY < 0)
                {
                    dY = -dY;
                    yStep = -1;
                }

                int x = startCoordinates.X;
                int y = startCoordinates.Y;

                Vertex startPoint = start;

                while (dX > 1 || dY > 1)
                {
                    if (dX > dY)
                    {
                        x += xStep;
                        dX--;
                    }
                    else if (dY > dX)
                    {
                        y += yStep;
                        dY--;
                    }
                    else
                    {
                        x += xStep;
                        dX--;
                        y += yStep;
                        dY--;
                    }

                    Vertex endPoint = result.AddVertex(x, y);
                    result.AddEdge(startPoint, endPoint);
                    startPoint = endPoint;
                }

                result.AddEdge(startPoint, end);
            }

            result.SetEnd(endVertexIndex);

            return result;
        }

        /// <summary>
        /// Process a generation to produce the individuals which will make up the next generation
        /// </summary>
        /// <param name="source">The current generation</param>
        /// <param name="destination">An empty collection of individuals to be populated</param>
        public void Operate(IGeneration source, ArrayList destination)
        {
            int i = 0;
            while (destination.Count < source.Count)
            {
                int j = 0;
                while (destination.Count < source.Count && j <= i)
                {
                    destination.Add(Mutate((RoadNetwork)source[j].Individual));
                    j++;
                }

                i++;
            }
        }

        /// <summary>
        /// Randomly alter a RoadNetwork to Produce a slightly different RoadNetwork
        /// </summary>
        /// <param name="source">The RoadNetwork to mutate</param>
        /// <returns>The mutated RoadNetwork</returns>
        public static RoadNetwork Mutate(RoadNetwork source)
        {            
            Map map = source.Map;
            int mapWidth = map.Width;
            int mapHeight = map.Height;

            int maxXChange = 1 + mapWidth / 10;
            int maxYChange = 1 + mapHeight / 10;

            source.ClearCopies();
            source.SetVisited(false);
            source.SetBroken(true);

            RoadNetwork destination = new RoadNetwork(map);
            int endVertexIndex = -1;

            LinkedList<Vertex> vertexStack = new LinkedList<Vertex>();
            source.Start.Visited = true;
            vertexStack.AddFirst(source.Start);

            while (vertexStack.Count > 0)
            {
                Vertex vertex = vertexStack.First();
                vertexStack.RemoveFirst();

                List<Vertex> nextVertices = new List<Vertex>();
                for (int i = 0; i < vertex.EdgeCount; i++)
                {
                    Edge edge = vertex.GetEdge(i);
                    Vertex nextVertex = edge.End;

                    if (!nextVertex.Visited)
                    {
                        edge.Broken = false;
                        nextVertex.Visited = true;
                        nextVertices.Add(nextVertex);
                    }
                }

                //If this vertex is a leaf of the tree and not the end vertex it has a 25% chance of
                //begin removed.
                if (nextVertices.Count > 0 || vertex == source.End || random.Next(4) > 0)
                {                    
                    Coordinates coordinates = vertex.Coordinates;

                    if (vertex != source.Start && vertex != source.End && random.Next(4) == 0)
                    {
                        coordinates = RandomAdjacentPoint(vertex.Coordinates);
                    }

                    int index = destination.AddVertexUnique(vertex.Coordinates);
                    vertex.Copy = destination.GetVertex(index);

                    if (vertex == source.End)
                    {
                        endVertexIndex = index;
                    }
                }

                //Shuffle Vertices
                for (int n = nextVertices.Count - 1; n > 0; n--)
                {
                    int m = random.Next(n + 1);
                    Vertex temp = nextVertices[m];
                    nextVertices[m] = nextVertices[n];
                    nextVertices[n] = temp;
                }

                //Push vertices onto stack in shiffled order.
                foreach (Vertex nextVertex in nextVertices)
                {
                    vertexStack.AddFirst(nextVertex);
                }
            }

            for (int i = 0; i < source.EdgeCount; i++)
            {
                Edge edge = source.GetEdge(i);

                if ((!edge.Broken || random.Next(4) > 0) && edge.Start.Copy != null && edge.End.Copy != null)
                {
                    StepPath(destination, edge.Start.Copy, edge.End.Copy);                    
                }
            }

            int newVertices = random.Next(20);
            for (int i = 0; i < newVertices; i++)
            {
                Vertex startVertex = destination.GetVertex(random.Next(destination.VertexCount));
                int index = destination.AddVertexUnique(RandomAdjacentPoint(startVertex.Coordinates));
                Vertex endVertex = destination.GetVertex(index);
                destination.AddEdge(startVertex, endVertex);
            }
            
            if (endVertexIndex == -1)
            {
                throw new Exception("End vertex not found.");
            }
            else
            {
                destination.SetEnd(endVertexIndex);
            }

            return destination;
        }

        /// <summary>
        /// Randomly choose an adjacent point.
        /// </summary>
        /// <param name="coordinates">The starting point</param>
        /// <returns>A point adjacent to the starting point</returns>
        private static Coordinates RandomAdjacentPoint(Coordinates coordinates)
        {
            int x = coordinates.X;
            int y = coordinates.Y;

            switch (random.Next(8))
            {
                case 0:
                    x++;
                    break;
                case 1:
                    x++;
                    y++;
                    break;
                case 2:
                    y++;
                    break;
                case 3:
                    x--;
                    y++;
                    break;
                case 4:
                    x--;
                    break;
                case 5:
                    x--;
                    y--;
                    break;
                case 6:
                    y--;
                    break;
                case 7:
                    x++;
                    y--;
                    break;
            }

            return new Coordinates(x, y);
        }

        /// <summary>
        /// Make a path between two vertices in a RoadNetwork out of a number of edges connecting adjacent points.
        /// </summary>
        /// <param name="network">The RoadNetwork to make the path in</param>
        /// <param name="start">The start Vertex of the path</param>
        /// <param name="end">The end Vertex of the path</param>
        public static void StepPath(RoadNetwork network, Vertex start, Vertex end)
        {
            int dX = end.Coordinates.X - start.Coordinates.X;
            int dY = end.Coordinates.Y - start.Coordinates.Y;

            int xStep = 1;
            if (dX < 0)
            {
                dX = -dX;
                xStep = -1;
            }

            int yStep = 1;
            if (dY < 0)
            {
                dY = -dY;
                yStep = -1;
            }
            
            int x = start.Coordinates.X;
            int y = start.Coordinates.Y;

            Vertex startVertex = start;
            
            while (dX > 1 || dY > 1)
            {
                if (dX > dY)
                {
                    x += xStep;
                    dX--;
                }
                else if (dY > dX)
                {
                    y += yStep;
                    dY--;
                }
                else
                {
                    x += xStep;
                    dX--;
                    y += yStep;
                    dY--;
                }

                int index = network.AddVertexUnique(x, y);
                Vertex endVertex = network.GetVertex(index);
                network.AddEdge(startVertex, endVertex);
                startVertex = endVertex;
            }

            network.AddEdge(startVertex, end);
        }
    }
}
